dist: xenial
language: cpp
sudo: required
compiler: gcc

addons:
  apt:
    packages:
      - libpng-dev
      - libjpeg8-dev
      - libtiff5-dev
      - libtbb-dev
      - libatlas-base-dev

matrix:
  include:
    - env: CCTAG_WITH_CUDA=ON CUDA_VERSION_MAJOR="9" CUDA_VERSION_MINOR="2" CUDA_PKG_LONGVERSION="${CUDA_VERSION_MAJOR}.${CUDA_VERSION_MINOR}.148-1" CUDA_PKG_VERSION="${CUDA_VERSION_MAJOR}-${CUDA_VERSION_MINOR}"
    - env: CCTAG_WITH_CUDA=ON CUDA_VERSION_MAJOR="10" CUDA_VERSION_MINOR="2" CUDA_PKG_LONGVERSION="${CUDA_VERSION_MAJOR}.${CUDA_VERSION_MINOR}.89-1" CUDA_PKG_VERSION="${CUDA_VERSION_MAJOR}-${CUDA_VERSION_MINOR}"
    - env: CCTAG_WITH_CUDA=ON CUDA_VERSION_MAJOR="11" CUDA_VERSION_MINOR="0" CUDA_PKG_LONGVERSION="${CUDA_VERSION_MAJOR}.${CUDA_VERSION_MINOR}.2-1" CUDA_PKG_VERSION="${CUDA_VERSION_MAJOR}-${CUDA_VERSION_MINOR}"
    - env: CCTAG_WITH_CUDA=OFF


env:
  global:
    - NUM_CPU="`grep processor /proc/cpuinfo | wc -l`"; echo $NUM_CPU
    - BUILD_TYPE="RELEASE"
    - BUILD_SYSTEM="`uname -s`"
    - BUILD_PROCESSOR="`uname -p`"
    - DEPS_INSTALL_PATH=${TRAVIS_BUILD_DIR}/../AliceVisionDependencies/install-deps
    - CCTAG_SOURCE=${TRAVIS_BUILD_DIR}
    - CCTAG_BUILD=${TRAVIS_BUILD_DIR}/build
    - CCTAG_INSTALL=${CCTAG_BUILD}/install
    - CCTAG_BUILD_VARIANT=${TRAVIS_BUILD_DIR}/build
    - CCTAG_INSTALL_VARIANT=${CCTAG_BUILD_VARIANT}/install
    - CCTAG_SOURCE_APP=$CCTAG_SOURCE/src/applications
    - CCTAG_BUILD_APP=${CCTAG_SOURCE_APP}/build

before_install:
 - date -u
 - uname -a
 - if [[ ${TRAVIS_OS_NAME} == "linux" ]]; then
     lsb_release -a;
   elif [[ ${TRAVIS_OS_NAME} == "osx" ]]; then
     sw_vers -productVersion;
   fi
 - ccache -s
 - gem install coveralls-lcov

install:
  # CUDA (only if needed)
  - UBUNTU_VERSION=ubuntu1604
  - >
     if [ "${CCTAG_WITH_CUDA}" = "ON" ]; then
        if [ ${CUDA_VERSION_MAJOR} -lt 11 ]; then
           CUDA_REPO_PKG=cuda-repo-${UBUNTU_VERSION}_${CUDA_PKG_LONGVERSION}_amd64.deb
           wget http://developer.download.nvidia.com/compute/cuda/repos/${UBUNTU_VERSION}/x86_64/$CUDA_REPO_PKG
           travis_retry sudo apt-key adv --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/${UBUNTU_VERSION}/x86_64/7fa2af80.pub
           sudo dpkg -i $CUDA_REPO_PKG
           rm ${CUDA_REPO_PKG}
           travis_retry sudo apt-get -y update
           # cuda > 10.0 changed cublas naming
           if [ ${CUDA_VERSION_MAJOR} -lt 10 ]; then
                 CUBLAS_PKG=cuda-cublas-dev-$CUDA_PKG_VERSION
           else
                 CUBLAS_PKG=libcublas-dev
           fi
           travis_retry sudo apt-get install -y --no-install-recommends --allow-unauthenticated cuda-core-$CUDA_PKG_VERSION  cuda-cudart-dev-$CUDA_PKG_VERSION  ${CUBLAS_PKG} cuda-curand-dev-$CUDA_PKG_VERSION
           sudo ln -s /usr/local/cuda-${CUDA_VERSION_MAJOR}.${CUDA_VERSION_MINOR} /usr/local/cuda
        else
           wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/cuda-ubuntu1604.pin
           travis_retry sudo mv cuda-ubuntu1604.pin /etc/apt/preferences.d/cuda-repository-pin-600
           travis_retry sudo apt-key adv --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/7fa2af80.pub
           travis_retry sudo add-apt-repository "deb http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/ /"
           sudo apt-get update && sudo apt-get -y install cuda
        fi
     fi
  - ./ci/install-cmake.sh
  - ./ci/install-dependencies.sh

before_script:
  - . ./ci/env.sh
  - export CMAKE_PREFIX_PATH="${DEPS_INSTALL_PATH}"
  - export CTEST_OUTPUT_ON_FAILURE=1
  # patch tbb
  # https://software.intel.com/en-us/forums/intel-threading-building-blocks/topic/431422
  - sudo sed -i '345s/.*/\#if \(__GNUC__==4 \&\& __GNUC_MINOR__>=4 \&\& __GXX_EXPERIMENTAL_CXX0X__\) || __clang_major__ >= 3/' /usr/include/tbb/pipeline.h
  # Create build folder
  - mkdir --parent $CCTAG_BUILD
  - cd $CCTAG_BUILD
  # Classic release build
  - >
     cmake \
       -DCMAKE_INSTALL_PREFIX:PATH=${CCTAG_INSTALL} \
       -DCCTAG_WITH_CUDA:BOOL=${CCTAG_WITH_CUDA} \
       -DCMAKE_BUILD_TYPE:STRING=${BUILD_TYPE} \
       -DBUILD_SHARED_LIBS:BOOL=ON \
       -DOpenCV_DIR:PATH="${DEPS_INSTALL_PATH}/share/OpenCV" \
       -DEIGEN_INCLUDE_DIR_HINTS="${DEPS_INSTALL_PATH}" \
       . ${CCTAG_SOURCE}

script:
  # classic make install
  - make install -j 2 VERBOSE=1
  - make test

  # Test if it compiles as third party
  - cd $CCTAG_SOURCE_APP
  - mkdir --parent $CCTAG_BUILD_APP
  - cd $CCTAG_BUILD_APP
  - >
     cmake  \
       -DBUILD_SHARED_LIBS:BOOL=ON \
       -DCCTag_DIR:PATH=/${CCTAG_INSTALL}/lib/cmake/CCTag/ \
       -DOpenCV_DIR:PATH=${OPENCV_INSTALL}/share/OpenCV \
       -DCMAKE_INSTALL_PREFIX:PATH=`pwd`/install \
       . ${CCTAG_SOURCE_APP}
  - make install -j 2 VERBOSE=1

  # For builds without cuda test also another variant with
  # CCTAG_VISUAL_DEBUG and CCTAG_SERIALIZE
  - >
     if [ "${CCTAG_WITH_CUDA}" = "OFF" ]; then
        mkdir --parent $CCTAG_BUILD_VARIANT
        cd $CCTAG_BUILD_VARIANT
        cmake \
         -DBUILD_SHARED_LIBS:BOOL=ON \
         -DCMAKE_INSTALL_PREFIX:PATH=${CCTAG_INSTALL_VARIANT} \
         -DCCTAG_WITH_CUDA:BOOL=${CCTAG_WITH_CUDA} \
         -DCMAKE_BUILD_TYPE:STRING=${BUILD_TYPE} \
         -DCCTAG_VISUAL_DEBUG:BOOL=ON \
         -DCCTAG_SERIALIZE:BOOL=ON \
         -DOpenCV_DIR:PATH=${OPENCV_INSTALL}/share/OpenCV \
         . ${CCTAG_SOURCE}
        make install -j 2 VERBOSE=1
        make test
     fi

after_success:
  - du -hs ${OPENCV_INSTALL}

# Before uploading the new cache archive
before_cache:
  - ccache -s

cache:
  ccache: true
